<a href="https://colab.research.google.com/github/Syamkrishna123/ICTK_ML_AI_ASSIGNMENTS_AND_CASE_STUDIES/blob/main/Case_Study_03_Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
df= pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/mobile_price_classification.csv")
df.head()

battery_power  bluetooth  clock_speed  dual_sim  front_cam  4G  int_memory  \
0            842          0          2.2         0          1   0           7   
1           1021          1          0.5         1          0   1          53   
2            563          1          0.5         1          2   1          41   
3            615          1          2.5         0          0   0          10   
4           1821          1          1.2         0         13   1          44   

   m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0    0.6        188        2  ...         20       756  2549     9     7   
1    0.7        136        3  ...        905      1988  2631    17     3   
2    0.9        145        5  ...       1263      1716  2603    11     2   
3    0.8        131        6  ...       1216      1786  2769    16     8   
4    0.6        141        2  ...       1208      1212  1411     8     2   

   talk_time  three_g  touch_screen  wifi  price_range  
0         19        0             0     1            1  
1          7        1             1     0            2  
2          9        1             1     0            2  
3         11        1             0     0            2  
4         15        1             1     0            1  

[5 rows x 21 columns]

In [4]:
df.shape

(2000, 21)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   battery_power   2000 non-null   int64  
 1   bluetooth       2000 non-null   int64  
 2   clock_speed     2000 non-null   float64
 3   dual_sim        2000 non-null   int64  
 4   front_cam       2000 non-null   int64  
 5   4G              2000 non-null   int64  
 6   int_memory      2000 non-null   int64  
 7   m_dep           2000 non-null   float64
 8   mobile_wt       2000 non-null   int64  
 9   n_cores         2000 non-null   int64  
 10  primary_camera  2000 non-null   int64  
 11  px_height       2000 non-null   int64  
 12  px_width        2000 non-null   int64  
 13  ram             2000 non-null   int64  
 14  sc_h            2000 non-null   int64  
 15  sc_w            2000 non-null   int64  
 16  talk_time       2000 non-null   int64  
 17  three_g         2000 non-null   i

In [6]:
df.describe()

battery_power  bluetooth  clock_speed     dual_sim    front_cam  \
count    2000.000000  2000.0000  2000.000000  2000.000000  2000.000000   
mean     1238.518500     0.4950     1.522250     0.509500     4.309500   
std       439.418206     0.5001     0.816004     0.500035     4.341444   
min       501.000000     0.0000     0.500000     0.000000     0.000000   
25%       851.750000     0.0000     0.700000     0.000000     1.000000   
50%      1226.000000     0.0000     1.500000     1.000000     3.000000   
75%      1615.250000     1.0000     2.200000     1.000000     7.000000   
max      1998.000000     1.0000     3.000000     1.000000    19.000000   

                4G   int_memory        m_dep    mobile_wt      n_cores  ...  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000  ...   
mean      0.521500    32.046500     0.501750   140.249000     4.520500  ...   
std       0.499662    18.145715     0.288416    35.399655     2.287837  ...   
min       0.000000     2.000000     0.100000    80.000000     1.000000  ...   
25%       0.000000    16.000000     0.200000   109.000000     3.000000  ...   
50%       1.000000    32.000000     0.500000   141.000000     4.000000  ...   
75%       1.000000    48.000000     0.800000   170.000000     7.000000  ...   
max       1.000000    64.000000     1.000000   200.000000     8.000000  ...   

         px_height     px_width          ram         sc_h         sc_w  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean    645.108000  1251.515500  2124.213000    12.306500     5.767000   
std     443.780811   432.199447  1084.732044     4.213245     4.356398   
min       0.000000   500.000000   256.000000     5.000000     0.000000   
25%     282.750000   874.750000  1207.500000     9.000000     2.000000   
50%     564.000000  1247.000000  2146.500000    12.000000     5.000000   
75%     947.250000  1633.000000  3064.500000    16.000000     9.000000   
max    1960.000000  1998.000000  3998.000000    19.000000    18.000000   

         talk_time      three_g  touch_screen         wifi  price_range  
count  2000.000000  2000.000000   2000.000000  2000.000000  2000.000000  
mean     11.011000     0.761500      0.503000     0.507000     1.500000  
std       5.463955     0.426273      0.500116     0.500076     1.118314  
min       2.000000     0.000000      0.000000     0.000000     0.000000  
25%       6.000000     1.000000      0.000000     0.000000     0.750000  
50%      11.000000     1.000000      1.000000     1.000000     1.500000  
75%      16.000000     1.000000      1.000000     1.000000     2.250000  
max      20.000000     1.000000      1.000000     1.000000     3.000000  

[8 rows x 21 columns]

In [7]:
data= df.drop('price_range',axis=1)
label=df['price_range']

In [8]:
data.columns

Index(['battery_power', 'bluetooth', 'clock_speed', 'dual_sim', 'front_cam',
       '4G', 'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'primary_camera',
       'px_height', 'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi'],
      dtype='object')

In [9]:
label.nunique()

4

In [42]:
data = data.values
data

array([[8.420e+02, 0.000e+00, 2.200e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [1.021e+03, 1.000e+00, 5.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [5.630e+02, 1.000e+00, 5.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       ...,
       [1.911e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [1.512e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        1.000e+00],
       [5.100e+02, 1.000e+00, 2.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00]])

In [13]:
label= label.values

In [44]:
label

array([1, 2, 2, ..., 3, 0, 3])

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler= StandardScaler()
data=scaler.fit_transform(data)
data

array([[-0.90259726, -0.9900495 ,  0.83077942, ..., -1.78686097,
        -1.00601811,  0.98609664],
       [-0.49513857,  1.0100505 , -1.2530642 , ...,  0.55964063,
         0.99401789, -1.01409939],
       [-1.5376865 ,  1.0100505 , -1.2530642 , ...,  0.55964063,
         0.99401789, -1.01409939],
       ...,
       [ 1.53077336, -0.9900495 , -0.76274805, ...,  0.55964063,
         0.99401789, -1.01409939],
       [ 0.62252745, -0.9900495 , -0.76274805, ...,  0.55964063,
         0.99401789,  0.98609664],
       [-1.65833069,  1.0100505 ,  0.58562134, ...,  0.55964063,
         0.99401789,  0.98609664]])

In [14]:
label = label.reshape(-1,1)

In [15]:
# now convert y labels to one hot encoder
from sklearn.preprocessing import OneHotEncoder
ohot = OneHotEncoder()
label = ohot.fit_transform(label)

In [12]:
label= pd.get_dummies(label)

In [13]:
label

0  1  2  3
0     0  1  0  0
1     0  0  1  0
2     0  0  1  0
3     0  0  1  0
4     0  1  0  0
...  .. .. .. ..
1995  1  0  0  0
1996  0  0  1  0
1997  0  0  0  1
1998  1  0  0  0
1999  0  0  0  1

[2000 rows x 4 columns]

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test= train_test_split(data,label, test_size=0.25, random_state=42)

In [18]:
X_train

array([[-1.65605439, -0.9900495 , -0.76274805, ...,  0.55964063,
        -1.00601811, -1.01409939],
       [-1.36013467,  1.0100505 , -0.51758998, ...,  0.55964063,
         0.99401789,  0.98609664],
       [-0.98682056, -0.9900495 , -0.88532709, ...,  0.55964063,
        -1.00601811,  0.98609664],
       ...,
       [ 1.34411631,  1.0100505 , -1.2530642 , ...,  0.55964063,
        -1.00601811,  0.98609664],
       [ 1.56719425, -0.9900495 , -0.76274805, ..., -1.78686097,
         0.99401789,  0.98609664],
       [-1.3737925 ,  1.0100505 , -1.13048516, ...,  0.55964063,
        -1.00601811, -1.01409939]])

In [52]:
X_train.shape

(1500, 20)

In [53]:
X_test.shape

(500, 20)

In [54]:
y_train.shape

(1500, 4)

In [55]:
y_test.shape

(500, 4)

In [15]:
from keras.models import Sequential
from keras.layers import Dense

In [16]:
model= Sequential()

In [17]:
model=Sequential()
model.add(Dense(8,activation='relu'))
model.add(Dense(6,activation='relu'))
model.add(Dense(4,activation='softmax'))

In [18]:
model.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [19]:
history = model.fit(X_train,y_train,epochs=105,validation_data=(X_test,y_test),batch_size=64)

Epoch 1/105
24/24 [==============================] - 1s 11ms/step - loss: 1.4674 - accuracy: 0.2653 - val_loss: 1.4536 - val_accuracy: 0.2460
Epoch 2/105
24/24 [==============================] - 0s 3ms/step - loss: 1.4142 - accuracy: 0.2753 - val_loss: 1.4118 - val_accuracy: 0.2540
Epoch 3/105
24/24 [==============================] - 0s 3ms/step - loss: 1.3835 - accuracy: 0.2800 - val_loss: 1.3835 - val_accuracy: 0.2600
Epoch 4/105
24/24 [==============================] - 0s 3ms/step - loss: 1.3610 - accuracy: 0.3000 - val_loss: 1.3605 - val_accuracy: 0.2980
Epoch 5/105
24/24 [==============================] - 0s 3ms/step - loss: 1.3394 - accuracy: 0.3213 - val_loss: 1.3386 - val_accuracy: 0.3200
Epoch 6/105
24/24 [==============================] - 0s 4ms/step - loss: 1.3161 - accuracy: 0.3493 - val_loss: 1.3153 - val_accuracy: 0.3680
Epoch 7/105
24/24 [==============================] - 0s 4ms/step - loss: 1.2901 - accuracy: 0.3867 - val_loss: 1.2879 - val_accuracy: 0.4040
Epoch 8/105


In [20]:
y_pred= model.predict(X_test)

16/16 [==============================] - 0s 2ms/step


In [26]:
y_pred

array([[9.9809253e-01, 1.9072032e-03, 2.4802321e-07, 8.0230729e-18],
       [8.3034451e-05, 9.7114565e-03, 9.9007463e-01, 1.3071827e-04],
       [1.5040630e-02, 9.8470575e-01, 2.5355152e-04, 6.9863697e-15],
       ...,
       [8.3878959e-08, 2.3218231e-06, 9.5555890e-01, 4.4438653e-02],
       [1.9430722e-14, 1.1741324e-15, 2.3323970e-04, 9.9976677e-01],
       [1.5087241e-01, 8.4864748e-01, 4.8014769e-04, 2.6416796e-12]],
      dtype=float32)

In [22]:
#lets do the inverse one hot encoding
pred = []
for i in range(len(y_pred)):
    pred.append(np.argmax(y_pred[i]))

In [25]:
test = []
for i in range(len(y_test)):
  test.append(np.argmax(y_test[i]))

KeyError: ignored

In [24]:
y_test

0  1  2  3
1860  1  0  0  0
353   0  0  1  0
1333  0  1  0  0
905   0  0  0  1
1289  0  1  0  0
...  .. .. .. ..
765   1  0  0  0
1356  0  1  0  0
408   0  0  1  0
1614  0  0  0  1
694   0  1  0  0

[500 rows x 4 columns]